# Generated by Django 2.2.3 on 2019-07-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=11)),
                ('host', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=50)),
            ],
        ),
    ]
